apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-production
  namespace: argocd
  annotations:
    argo.octopus.com/project: octopus-ai-escape-room
    argo.octopus.com/environment: production
spec:
  project: default
  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: "6.14.0"
      helm:
        valueFiles:
          - $values/helm/podinfo/values-production.yaml
    - repoURL: https://github.com/reggie-k/octopus-ai-escape-room.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
